name: Deploy Auth Service Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/auth-server/**"
      - "packages/db/**"
      - "packages/auth/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy auth service worker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build -F auth-service

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACC_ID }}
          workingDirectory: apps/auth-server
          secrets: |
            DATABASE_URL
            DATABASE_URL_POOLER
            BETTER_AUTH_SECRET
            DODO_PAYMENTS_API_KEY
            DODO_PAYMENTS_WEBHOOK_SECRET
            GITHUB_CLIENT_ID
            GITHUB_CLIENT_SECRET
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
            PRO_ID
            STARTER_ID
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_POOLER: ${{ secrets.DATABASE_URL_POOLER }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          DODO_PAYMENTS_API_KEY: ${{ secrets.DODO_PAYMENTS_API_KEY }}
          DODO_PAYMENTS_WEBHOOK_SECRET: ${{ secrets.DODO_PAYMENTS_WEBHOOK_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          PRO_ID: ${{ secrets.PRO_ID }}
          STARTER_ID: ${{ secrets.STARTER_ID }}
